[versions]
ktor = "3.4.0"
kotlinx-serialization = "1.10.0"
kotlinx-datetime = "0.7.1"
kotlin-test = "2.3.0"
bigquery = "2.58.0"
prometheus = "1.16.2"
logback = "1.5.27"
logstash = "9.0"
junit-jupiter = "6.0.2"

[libraries]
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin-test" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization"}
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime"}
bigquery = { module = "com.google.cloud:google-cloud-bigquery", version.ref = "bigquery"}
metrics-ktor = { module = "io.ktor:ktor-server-metrics-micrometer", version.ref = "ktor" }
metrics-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "prometheus" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-jupiter" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logstash = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash" }

[bundles]
ktor = [
    "ktor-server-core",
    "ktor-server-netty",
]
logging = [
    "logback",
    "logstash"
]