name: Build and deploy main
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
jobs:
  test-build-deploy:
    permissions:
      actions: read # for sarif
      contents: write # for dependency graph & sarif
      security-events: write # push sarif to github security
      id-token: write # for nais docker-build-push
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
      - uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884
      - name: Test & build
        run: ./gradlew test build
      - name: Build & push docker image + SBOM
        uses: nais/docker-build-push@87f920b0411b987d9a1fd4113aa384e1e3b54f2c
        id: docker-push
        with:
          team: appsec
          pull: true
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@f29f5a9d7b09a7c6b29859002d29d24e1674c884
      - name: Scan docker image for secrets
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
        with:
          image-ref: '${{ steps.docker-push.outputs.image }}'
          format: 'sarif'
          scanners: 'secret'
          output: 'trivy.sarif'
      - uses: github/codeql-action/upload-sarif@45cbd0c69e560cd9e7cd7f8c32362050c9b7ded2
        with:
          sarif_file: 'trivy.sarif'
  deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        id-token: write
    needs: test-build-deploy
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1
        env:
          RESOURCE: .nais/nais.yaml
          CLUSTER: prod-gcp
          IMAGE: ${{ needs.test-build-deploy.outputs.image }}
